package com.phantomwing.thesilverage.neoforge.datagen;

import com.phantomwing.thesilverage.TheSilverAge;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.DataGenerator;
import net.minecraft.data.PackOutput;
import net.minecraft.data.advancements.AdvancementProvider;
import net.minecraft.data.loot.LootTableProvider;
import net.minecraft.world.level.storage.loot.parameters.LootContextParamSets;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.data.event.GatherDataEvent;

import java.util.List;
import java.util.Set;
import java.util.concurrent.CompletableFuture;

// GatherDataEvent is a MOD-bus event. 1.21.4 reworked the event: there is no
// more includeServer()/includeClient() gating or getExistingFileHelper() — you
// just event.addProvider(provider) and the run args (--all/--client/--server)
// decide what actually emits.
@EventBusSubscriber(modid = TheSilverAge.MOD_ID, bus = EventBusSubscriber.Bus.MOD)
public class DataGenerators {
    // 1.21.4: GatherDataEvent is abstract — you must subscribe to a concrete
    // subclass (Client/Server). We use the Client event (fired by the clientData
    // run); its environment is a full client, so the server-side DataProviders
    // (recipes/loot/tags/...) added here run fine alongside the model providers.
    @SubscribeEvent
    public static void gatherData(GatherDataEvent.Client event) {
        DataGenerator generator = event.getGenerator();
        PackOutput output = generator.getPackOutput();
        CompletableFuture<HolderLookup.Provider> lookupProvider = event.getLookupProvider();

        event.addProvider(new ModRecipeProvider.Runner(output, lookupProvider));

        event.addProvider(new LootTableProvider(
                output,
                Set.of(),
                List.of(new LootTableProvider.SubProviderEntry(ModBlockLootTableProvider::new, LootContextParamSets.BLOCK)),
                lookupProvider));

        // 1.21.4: NeoForge's AdvancementProvider wrapper is gone — use vanilla's,
        // which takes a List<AdvancementSubProvider> (ModAdvancementProvider).
        event.addProvider(new AdvancementProvider(output, lookupProvider, List.of(new ModAdvancementProvider())));

        event.addProvider(new ModDataMapProvider(output, lookupProvider));

        // 1.21.4: block + item models are generated by a single vanilla-style
        // ModelProvider (registerModels(BlockModelGenerators, ItemModelGenerators)).
        event.addProvider(new ModModelProvider(output));

        ModBlockTagsProvider blockTagsProvider = event.addProvider(new ModBlockTagsProvider(output, lookupProvider));
        event.addProvider(new ModItemTagsProvider(output, lookupProvider, blockTagsProvider.contentsGetter()));
        event.addProvider(new ModBiomeTagsProvider(output, lookupProvider));
        event.addProvider(new ModEntityTypeTagsProvider(output, lookupProvider));

        event.addProvider(new ModGlobalLootModifierProvider(output, lookupProvider));

        event.addProvider(new ModDatapackProvider(output, lookupProvider));

        // MUST be registered LAST — post-processes the shared generated tree,
        // mirroring each neoforge:conditions block with a fabric:load_conditions
        // one so the single shared data gates identically on both loaders.
        event.addProvider(new FabricConditionsProvider(output));
    }
}
